AppBundle\Entity\Events:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\EventsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        eventName:
            type: string
            length: 255
            nullable: true
            unique: true
            column: event_name
        eventDate:
            type: date
            nullable: true
            column: event_date
        eventTopic:
            type: text
            column: event_topic
            nullable: true
        eventMentor:
            type: string
            length: 255
            column: event_mentor
            nullable: true
        eventCategory:
            type: integer
            column: event_category
            nullable: true
        eventMentorjob:
            type: string
            length: 255
            column: event_mentorjob
            nullable: true
        eventTime:
            type: time
            column: event_time
            nullable: true
        eventParticipant:
            type: string
            length: 255
            column: event_participant
            nullable: true
        eventPrice:
            type: string
            length: 255
            column: event_price
            nullable: true
        eventDetail:
            type: text
            column: event_detail
            nullable: true
        eventPhoto:
            type: string
            length: 255
            column: event_photo
            nullable: true
    lifecycleCallbacks: {  }
