AppBundle\Entity\Management:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ManagementRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        manageMonth:
            type: integer
            column: manage_month
        manageYear:
            type: integer
            column: manage_year
            nullable: true
        manageDataMember:
            type: string
            length: 255
            column: manage_datamember
            nullable: true
        manageDataUser:
            type: string
            length: 255
            column: manage_datauser
            nullable: true
        manageDatafb:
            type: string
            length: 255
            column: manage_datafb
            nullable: true
        manageDatatwitter:
            type: string
            length: 255
            column: manage_datatwitter
            nullable: true
        manageDataig:
            type: string
            length: 255
            column: manage_dataig
            nullable: true
        manageDataStartup:
            type: string
            length: 255
            column: manage_datastartup
            nullable: true
        manageDataCommunity:
            type: string
            length: 255
            column: manage_datacommunity
            
      
    lifecycleCallbacks: {  }
