AppBundle\Entity\Member:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\MemberRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        memberName:
            type: string
            length: 255
            column: member_name
        memberActivity:
            type: string
            length: 255
            column: member_activity
        memberTotal:
            type: string
            length: 255
            column: member_total
        memberGenre:
            type: integer
            column: member_genre
        memberStatus:
            type: integer
            column: member_status
        memberEmail:
            type: string
            length: 255
            column: member_email
        memberDate:
            type: date
            column: member_date
        memberPhone:
            type: string
            length: 20
            column: member_phone
    lifecycleCallbacks: {  }
