AppBundle\Entity\Operational:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\OperationalRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        operationalName:
            type: string
            length: 255
            column: Operational_name
        operationalCategory:
            type: integer
            nullable: true
            column: Operational_category
        operationalMonth:
            type: integer
            nullable: true
            column: Operational_month
        operationalYear:
            type: integer
            nullable: true
            column: Operational_year   
        operationalQty:
            type: string
            length: 255
            nullable: true
            column: Operational_qty
        operationalUnitprice:
            type: string
            length: 255
            column: Operational_unitprice
            nullable : true
        operationalTotal:
            type: string
            length: 255
            nullable: true
            column: Operational_total
    lifecycleCallbacks: {  }
